version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    labels:
      - "dependencies"
      - "automated pr"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
